window.__ModuleLoader__.load({
  id: '@ciaobye/dsh-sensenova-provider',
  factory: (require) => {
    var module = { exports: {} }, exports = module.exports
    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' })
    const React = require('react'), h = React.createElement
    const NS='llm-sensenova', LNS='settings.sensenova', PKG='@ciaobye/dsh-sensenova-provider', REF='SENSENOVA_API_KEY'
    const D={apiBase:'https://token.sensenova.cn/v1',keys:[{id:'default',label:'Default',apiKeyEnv:REF}],activeKey:'',modelKeyRules:[],visibleModels:[],cooldown429Ms:30000,maxCooldown429Ms:120000,connectTimeoutMs:45000,streamIdleTimeoutMs:60000,defaultContextWindow:131072}
    const RESET=['apiBase','activeKey','modelKeyRules','visibleModels','cooldown429Ms','maxCooldown429Ms','connectTimeoutMs','streamIdleTimeoutMs','defaultContextWindow']
    const zh={nav:'SenseNova',title:'SenseNova',intro:'管理多 Key 轮转、模型路由、模型白名单与运行状态。API Key 只保存到 DSH Credentials。',loading:'正在读取配置…',unavailable:'SenseNova 配置不可用，请确认 Host 插件已启用。',readonly:'当前设置文档为只读。',pool:'多 Key 轮转',poolHint:'首选 Key 不可用、401 或 429 时会自动故障转移。',preferred:'当前首选 Key',auto:'自动（第一个可用 Key）',refresh:'刷新',usable:'可用',cooldown:'429 冷却',disabled:'401 已禁用',missing:'未配置',last:'最近使用',resetState:'重置状态',name:'名称',secret:'API 密钥',source:'来源',writable:'可修改',readOnlySecret:'只读来源',show:'显示',hide:'隐藏',clear:'清除已存密钥',undo:'撤销清除',remove:'删除',addKey:'+ 添加 Key',keep:'留空保留已有密钥；输入新值并保存即可更换。',routing:'按模型切换 Key',routingHint:'第一条匹配规则优先；目标 Key 不可用时仍会自动切到其他可用 Key。',addRule:'添加规则',noRules:'尚未配置规则。',models:'模型',key:'首选 Key',up:'上移',down:'下移',allow:'模型白名单',allowHint:'只影响 DSH 模型选择器；空白名单表示显示全部模型。',showAll:'显示全部',refreshModels:'刷新模型',advanced:'高级设置',apiBase:'API 地址',cd:'429 默认冷却（毫秒）',maxCd:'429 最大冷却（毫秒）',connect:'连接/首字节超时（毫秒）',idle:'流空闲超时（毫秒）',context:'默认 Context Window',overridden:'已覆盖',reset:'重置',inherit:'将继承默认',quota:'Token Plan 用量',quotaHint:'官方公开 API 文档目前没有账户 credits / 5 小时窗口查询端点。本插件不会抓取控制台私有接口，也不会伪造额度数据。',save:'保存',saving:'保存中…',cancel:'取消',saved:'已保存',invalid:'配置无效：数值必须为正，最大冷却不能小于默认冷却，路由必须选择模型和有效 Key。',saveFail:'保存失败，请重试。',catalogFail:'模型目录读取失败，可稍后刷新。'}
    const en={...zh,nav:'SenseNova',title:'SenseNova',intro:'Manage multi-key failover, model routing, model visibility and runtime state. API keys are stored only in DSH Credentials.',loading:'Loading settings…',unavailable:'SenseNova settings are unavailable. Make sure the Host plugin is enabled.',readonly:'The settings document is read-only.',pool:'Multi-key rotation',poolHint:'A preferred key still fails over when unavailable, rejected with 401, or cooling down after 429.',preferred:'Preferred key',auto:'Automatic (first usable key)',refresh:'Refresh',usable:'Usable',cooldown:'429 cooldown',disabled:'Disabled after 401',missing:'Not configured',last:'Last used',resetState:'Reset state',name:'Label',secret:'API key',source:'Source',writable:'Writable',readOnlySecret:'Read-only source',show:'Show',hide:'Hide',clear:'Clear stored key',undo:'Undo clear',remove:'Remove',addKey:'+ Add key',keep:'Leave blank to keep the stored key; enter a new value and save to replace it.',routing:'Route models to keys',routingHint:'First matching rule wins; an unavailable preferred key still fails over.',addRule:'Add rule',noRules:'No routing rules configured.',models:'Models',key:'Preferred key',up:'Move up',down:'Move down',allow:'Model allowlist',allowHint:'Only narrows DSH model pickers; an empty allowlist means all models.',showAll:'Show all',refreshModels:'Refresh models',advanced:'Advanced',apiBase:'API base',cd:'Default 429 cooldown (ms)',maxCd:'Maximum 429 cooldown (ms)',connect:'Connect/first-byte timeout (ms)',idle:'Stream idle timeout (ms)',context:'Default context window',overridden:'Overridden',reset:'Reset',inherit:'Will inherit default',quota:'Token Plan usage',quotaHint:'The public API documentation currently exposes no account credits / 5-hour quota endpoint. This plugin does not scrape private console APIs or invent quota data.',save:'Save',saving:'Saving…',cancel:'Cancel',saved:'Saved',invalid:'Invalid configuration: numbers must be positive, maximum cooldown cannot be lower than default, and routing rules need models plus a valid key.',saveFail:'Save failed; retry.',catalogFail:'Could not load the model catalog; retry later.'}
    const clone=x=>JSON.parse(JSON.stringify(x)), own=(o,k)=>!!o&&typeof o==='object'&&Object.prototype.hasOwnProperty.call(o,k), uniq=a=>[...new Set((Array.isArray(a)?a:[]).filter(x=>typeof x==='string').map(x=>x.trim()).filter(Boolean))]
    function norm(v){const r=v&&typeof v==='object'?v:{},src=Array.isArray(r.keys)&&r.keys.length?r.keys:D.keys,keys=src.map((x,i)=>({id:typeof x?.id==='string'&&x.id.trim()?x.id.trim():`key-${i+1}`,label:typeof x?.label==='string'&&x.label.trim()?x.label.trim():`Key ${i+1}`,ref:typeof x?.apiKeyEnv==='string'&&x.apiKeyEnv.trim()?x.apiKeyEnv.trim():(i?`${REF}_${i+1}`:REF),keyText:'',configured:false,source:'',credentialWritable:true,clear:false,status:'missing',cooldownUntil:0})),ids=new Set(keys.map(k=>k.id));return{apiBase:typeof r.apiBase==='string'&&r.apiBase.trim()?r.apiBase:D.apiBase,keys,activeKey:typeof r.activeKey==='string'&&ids.has(r.activeKey)?r.activeKey:'',modelKeyRules:Array.isArray(r.modelKeyRules)?r.modelKeyRules.map(x=>({models:uniq(x?.models),keyId:typeof x?.keyId==='string'?x.keyId:''})).filter(x=>x.models.length&&ids.has(x.keyId)):[],visibleModels:uniq(r.visibleModels),cooldown429Ms:String(Number.isFinite(r.cooldown429Ms)?r.cooldown429Ms:D.cooldown429Ms),maxCooldown429Ms:String(Number.isFinite(r.maxCooldown429Ms)?r.maxCooldown429Ms:D.maxCooldown429Ms),connectTimeoutMs:String(Number.isFinite(r.connectTimeoutMs)?r.connectTimeoutMs:D.connectTimeoutMs),streamIdleTimeoutMs:String(Number.isFinite(r.streamIdleTimeoutMs)?r.streamIdleTimeoutMs:D.streamIdleTimeoutMs),defaultContextWindow:String(Number.isFinite(r.defaultContextWindow)?r.defaultContextWindow:D.defaultContextWindow)}}
    function ser(c){return{apiBase:c.apiBase.trim().replace(/\/+$/,''),keys:c.keys.map(k=>({id:k.id,label:k.label.trim(),apiKeyEnv:k.ref})),activeKey:c.activeKey||'',modelKeyRules:c.modelKeyRules.map(r=>({models:uniq(r.models),keyId:r.keyId})),visibleModels:uniq(c.visibleModels),cooldown429Ms:Math.floor(Number(c.cooldown429Ms)),maxCooldown429Ms:Math.floor(Number(c.maxCooldown429Ms)),connectTimeoutMs:Math.floor(Number(c.connectTimeoutMs)),streamIdleTimeoutMs:Math.floor(Number(c.streamIdleTimeoutMs)),defaultContextWindow:Math.floor(Number(c.defaultContextWindow))}}
    class Controller{
      constructor(scope,creds,llm){this.scope=scope;this.creds=creds;this.llm=llm;this.listeners=new Set;this.base=norm();this.inherited=norm(D);this.draft=clone(this.base);this.resets=new Set;this.overrides=new Set;this.removed=[];this.runtime={keys:[],lastUsedId:'',now:Date.now()};this.catalog=[];this.runtimeApi=null;this.status='loading';this.writable=false;this.saving=false;this.failed=false;this.saved=0;this.catalogFailed=false;this.disposeScope=scope.subscribe(()=>this.load());this.load(true)}
      dispose(){this.disposeScope?.();this.listeners.clear()} subscribe(f){this.listeners.add(f);return()=>this.listeners.delete(f)} emit(){for(const f of this.listeners)try{f()}catch(e){console.error(e)}}
      dirty(){return JSON.stringify(ser(this.draft))!==JSON.stringify(ser(this.base))||this.resets.size>0||this.draft.keys.some(k=>k.keyText.trim()||k.clear)||this.removed.length>0}
      valid(){if(!this.draft.apiBase.trim()||!this.draft.keys.length)return false;const ids=new Set,refs=new Set;for(const k of this.draft.keys){if(!k.id||!k.label.trim()||!k.ref||ids.has(k.id)||refs.has(k.ref))return false;ids.add(k.id);refs.add(k.ref)}if(this.draft.activeKey&&!ids.has(this.draft.activeKey))return false;for(const r of this.draft.modelKeyRules)if(!r.models.length||!ids.has(r.keyId))return false;for(const f of ['cooldown429Ms','maxCooldown429Ms','connectTimeoutMs','streamIdleTimeoutMs','defaultContextWindow']){const n=Number(this.draft[f]);if(!Number.isFinite(n)||n<=0)return false}return Number(this.draft.maxCooldown429Ms)>=Number(this.draft.cooldown429Ms)}
      state(){return{...clone(this.draft),available:this.status==='ready',loading:this.status==='loading',writable:this.writable,saving:this.saving,failed:this.failed,saved:this.saved,dirty:this.dirty(),valid:this.valid(),resets:[...this.resets],overrides:Object.fromEntries(RESET.map(f=>[f,this.overrides.has(f)&&!this.resets.has(f)])),runtime:clone(this.runtime),catalog:clone(this.catalog),catalogFailed:this.catalogFailed}}
      load(force=false){const s=this.scope.getSnapshot();this.status=s.status;this.writable=!!s.writable;if(s.status==='ready'&&(force||(!this.dirty()&&!this.saving))){this.base=norm(s.value);this.draft=clone(this.base);this.inherited=norm(s.base??D);this.overrides=new Set(RESET.filter(f=>own(s.user,f)));this.resets.clear();this.removed=[];this.failed=false;void this.refreshCreds();void this.refreshRuntime();if(!this.catalog.length)void this.refreshModels()}this.emit()}
      edit(f,v){this.draft[f]=v;this.resets.delete(f);this.failed=false;this.emit()} reset(f){if(!RESET.includes(f))return;if(this.overrides.has(f)){this.draft[f]=clone(this.inherited[f]);this.resets.add(f)}else{this.draft[f]=clone(this.base[f]);this.resets.delete(f)}this.emit()}
      editKey(id,f,v){const k=this.draft.keys.find(x=>x.id===id);if(k&&(f==='label'||f==='keyText'))k[f]=v;this.emit()} toggleClear(id){const k=this.draft.keys.find(x=>x.id===id);if(k&&k.credentialWritable){k.clear=!k.clear;if(k.clear)k.keyText='';this.emit()}}
      addKey(){const ids=new Set(this.draft.keys.map(k=>k.id)),refs=new Set(this.draft.keys.map(k=>k.ref));let n=2;while(ids.has(`sn-${n}`)||refs.has(`${REF}_${n}`))n++;this.draft.keys.push({id:`sn-${n}`,label:`SenseNova ${n}`,ref:`${REF}_${n}`,keyText:'',configured:false,source:'',credentialWritable:true,clear:false,status:'missing',cooldownUntil:0});this.emit()}
      removeKey(id){if(this.draft.keys.length<=1)return;const k=this.draft.keys.find(x=>x.id===id);if(k)this.removed.push({ref:k.ref,writable:k.credentialWritable});this.draft.keys=this.draft.keys.filter(x=>x.id!==id);if(this.draft.activeKey===id)this.draft.activeKey='';this.draft.modelKeyRules=this.draft.modelKeyRules.filter(r=>r.keyId!==id);this.emit()}
      addRule(){this.draft.modelKeyRules.push({models:[],keyId:this.draft.keys[0]?.id||''});this.resets.delete('modelKeyRules');this.emit()} removeRule(i){this.draft.modelKeyRules.splice(i,1);this.resets.delete('modelKeyRules');this.emit()} moveRule(i,d){const j=i+d;if(j<0||j>=this.draft.modelKeyRules.length)return;const [r]=this.draft.modelKeyRules.splice(i,1);this.draft.modelKeyRules.splice(j,0,r);this.resets.delete('modelKeyRules');this.emit()} editRule(i,f,v){const r=this.draft.modelKeyRules[i];if(r){r[f]=f==='models'?uniq(v):v;this.resets.delete('modelKeyRules');this.emit()}}
      toggleModel(id,on){const all=this.catalog.map(m=>m.id),set=new Set(this.draft.visibleModels.length?this.draft.visibleModels:all);on?set.add(id):set.delete(id);this.draft.visibleModels=set.size===all.length?[]:all.filter(x=>set.has(x));this.resets.delete('visibleModels');this.emit()} showAll(){this.draft.visibleModels=[];this.resets.delete('visibleModels');this.emit()}
      setRuntimeApi(api){this.runtimeApi=api;void this.refreshRuntime();void this.refreshModels()}
      mergeRuntime(){const m=new Map((this.runtime.keys||[]).map(x=>[x.id,x]));for(const t of [this.draft,this.base])for(const k of t.keys){const r=m.get(k.id);if(r){k.status=r.status;k.cooldownUntil=r.cooldownUntil||0;if(r.configured)k.configured=true}}}
      async refreshCreds(){if(!this.creds?.describe)return;const refs=this.draft.keys.map(k=>k.ref);try{const r=await this.creds.describe(refs);if(!r?.ok)return;for(const t of [this.draft,this.base])for(const k of t.keys){const i=r.value?.[k.ref];k.configured=!!i?.configured;k.source=typeof i?.source==='string'?i.source:'';k.credentialWritable=i?.writable!==false}this.mergeRuntime();this.emit()}catch(e){console.error(e)}}
      async refreshRuntime(){if(!this.runtimeApi?.runtime)return;try{const r=await this.runtimeApi.runtime();if(r?.ok){this.runtime=r.value;this.mergeRuntime();this.emit()}}catch(e){console.error(e)}}
      async resetRuntime(id){if(!this.runtimeApi?.reset)return;try{const r=await this.runtimeApi.reset(id);if(r?.ok){this.runtime=r.value;this.mergeRuntime();this.emit()}}catch(e){console.error(e)}}
      async refreshModels(){if(this._loading){this._modelsQueued=true;return}this._loading=true;this.catalogFailed=false;this.emit();try{let ms;if(this.runtimeApi?.models){const r=await this.runtimeApi.models();if(r?.ok)ms=r.value?.models;else throw Error(r?.error?.message||'models failed')}else if(this.llm?.discoverModels){const r=await this.llm.discoverModels(NS,{provider:'sensenova'});if(r?.ok)ms=r.value;else throw Error(r?.error?.message||'models failed')}this.catalog=Array.isArray(ms)?ms.filter(x=>x&&typeof x.id==='string').map(x=>({id:x.id,name:typeof x.name==='string'?x.name:x.id})):[]}catch(e){this.catalogFailed=true;console.error(e)}finally{this._loading=false;if(this._modelsQueued){this._modelsQueued=false;void this.refreshModels()}else{this.emit()}}}
      discard(){this.draft=clone(this.base);this.resets.clear();this.removed=[];this.failed=false;void this.refreshCreds();this.emit()}
      async save(){if(this.saving||!this.writable||!this.valid())return;this.saving=true;this.failed=false;this.emit();try{const n=ser(this.draft),b=ser(this.base),ops=[];for(const f of Object.keys(n)){if(this.resets.has(f))ops.push({op:'unset',path:[f]});else if(JSON.stringify(n[f])!==JSON.stringify(b[f]))ops.push({op:'set',path:[f],value:n[f]})}if(ops.length)await this.scope.mutate(ops);for(const k of this.draft.keys){if(k.clear&&k.credentialWritable&&this.creds?.unset){const r=await this.creds.unset(k.ref);if(r?.ok===false)throw Error(r.error?.message)}else if(k.keyText.trim()&&k.credentialWritable&&this.creds?.set){const r=await this.creds.set(k.ref,k.keyText.trim());if(r?.ok===false)throw Error(r.error?.message)}}for(const x of this.removed)if(x.writable&&this.creds?.unset)await this.creds.unset(x.ref);this.base=norm(n);this.draft=clone(this.base);this.resets.clear();this.removed=[];this.saved++;await this.refreshCreds();await this.refreshRuntime();await this.refreshModels()}catch(e){this.failed=true;console.error(e)}finally{this.saving=false;this.emit()}}
    }
    function store(c){let s=c.state();const ls=new Set,dispose=c.subscribe(()=>{s=c.state();for(const f of ls)f()});return{getSnapshot:()=>s,subscribe(f){ls.add(f);return()=>ls.delete(f)},dispose}}
    const CSS=`.sn-section{max-width:720px;color:var(--dsw-alias-label-primary);display:flex;flex-direction:column;gap:12px}.sn-title{margin:0;font-size:18px;font-weight:600}.sn-intro,.sn-hint,.sn-meta{margin:0;color:var(--dsw-alias-label-tertiary);font-size:13px;line-height:1.5}.sn-card{border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-3);border-radius:12px;padding:4px 16px}.sn-head,.sn-fieldHead,.sn-row,.sn-actions{display:flex;align-items:center;gap:8px}.sn-head{padding:12px 0}.sn-head h3,.sn-label{font-size:13px;font-weight:500;margin:0;flex:1}.sn-field,.sn-item,.sn-rule{padding:12px 0;border-top:1px solid var(--dsw-alias-border-l2)}.sn-field{display:flex;flex-direction:column;gap:6px}.sn-input,.sn-select{width:100%;height:34px;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);border-radius:8px;padding:0 12px;box-sizing:border-box;font:inherit;font-size:13px}.sn-multi{height:110px;padding:6px 8px}.sn-grid{display:grid;grid-template-columns:1fr 1.5fr;gap:12px}.sn-badge{white-space:nowrap;background:var(--dsw-alias-bg-module-platform);color:var(--dsw-alias-label-secondary);border-radius:999px;padding:1px 8px;font-size:11px;line-height:17px}.sn-link{border:0;background:transparent;color:var(--dsw-alias-label-secondary);font:inherit;font-size:12px;cursor:pointer;padding:0}.sn-btn{height:32px;border:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-layer-1);color:var(--dsw-alias-label-primary);border-radius:8px;padding:0 12px;font:inherit;font-size:12px;cursor:pointer;white-space:nowrap}.sn-primary{background:var(--dsw-alias-brand-primary);border-color:var(--dsw-alias-brand-primary);color:#fff}.sn-danger,.sn-error{color:var(--dsw-alias-label-error)}.sn-btn:disabled,.sn-link:disabled,.sn-input:disabled,.sn-select:disabled{opacity:.45;cursor:default}.sn-spacer{flex:1}.sn-footer{display:flex;align-items:center;justify-content:flex-end;gap:8px}.sn-error,.sn-ok{margin:0;font-size:12px;flex:1}.sn-models{max-height:220px;overflow:auto}.sn-check{display:flex;align-items:center;gap:8px;padding:7px 0;border-top:1px solid var(--dsw-alias-border-l2);font-size:12px}.sn-advanced{width:100%;padding:12px 0;border:0;background:transparent;color:inherit;font:inherit;font-size:13px;text-align:left;cursor:pointer}.sn-note{border-left:2px solid var(--dsw-alias-border-l2);padding:8px 12px;margin:8px 0 12px}.sn-modelCard{padding:10px 0;display:flex;gap:8px;align-items:center}@media(max-width:700px){.sn-grid{grid-template-columns:1fr}}`
    function css(){if(document.getElementById('dsh-sensenova-provider-style'))return()=>{};const s=document.createElement('style');s.id='dsh-sensenova-provider-style';s.textContent=CSS;document.head.appendChild(s);return()=>s.remove()}
    const R=({state,f,t,disabled,onReset})=>h('span',{className:'sn-actions'},state.overrides[f]?h('span',{className:'sn-badge'},state.resets.includes(f)?t('inherit'):t('overridden')):null,h('button',{className:'sn-link',disabled:disabled||(!state.overrides[f]&&!state.resets.includes(f)),onClick:onReset},t('reset')))
    function Field({state,f,label,t,disabled,edit,reset}){return h('div',{className:'sn-field'},h('div',{className:'sn-fieldHead'},h('span',{className:'sn-label'},label),h(R,{state,f,t,disabled,onReset:()=>reset(f)})),h('input',{className:'sn-input',value:state[f],disabled,onChange:e=>edit(f,e.target.value)}))}
    function Page(p){const s=p.useSenseNovaSettings(x=>x),t=p.t,[adv,setAdv]=React.useState(false),[showSecrets,setShowSecrets]=React.useState(false),disabled=!s.writable||s.saving;if(s.loading)return h('p',{className:'sn-hint'},t('loading'));if(!s.available)return h('p',{className:'sn-error'},t('unavailable'));const chosen=new Set(s.visibleModels.length?s.visibleModels:s.catalog.map(m=>m.id));return h('section',{className:'sn-section'},h('h2',{className:'sn-title'},t('title')),h('p',{className:'sn-intro'},t('intro')),!s.writable?h('p',{className:'sn-error'},t('readonly')):null,
      h('div',{className:'sn-card'},h('div',{className:'sn-head'},h('h3',null,t('pool')),h('span',{className:'sn-spacer'}),h('button',{className:'sn-link',type:'button',onClick:()=>setShowSecrets(v=>!v)},showSecrets?t('hide'):t('show')),h('button',{className:'sn-link',onClick:p.refreshRuntime},t('refresh'))),h('p',{className:'sn-hint'},t('poolHint')),h('div',{className:'sn-field'},h('div',{className:'sn-fieldHead'},h('span',{className:'sn-label'},t('preferred')),h(R,{state:s,f:'activeKey',t,disabled,onReset:()=>p.resetField('activeKey')})),h('select',{className:'sn-select',value:s.activeKey,disabled,onChange:e=>p.edit('activeKey',e.target.value)},h('option',{value:''},t('auto')),s.keys.map(k=>h('option',{key:k.id,value:k.id},k.label)))),s.keys.map(k=>h('div',{className:'sn-item',key:k.id},h('div',{className:'sn-row'},h('strong',{className:'sn-label'},k.label),s.runtime.lastUsedId===k.id?h('span',{className:'sn-badge'},t('last')):null,h('span',{className:'sn-badge'},t(k.status==='disabled'?'disabled':k.status==='cooldown'?'cooldown':k.configured?'usable':'missing'))),h('div',{className:'sn-grid'},h('label',{className:'sn-field'},h('span',{className:'sn-label'},t('name')),h('input',{className:'sn-input',value:k.label,disabled,onChange:e=>p.editKey(k.id,'label',e.target.value)})),h('label',{className:'sn-field'},h('span',{className:'sn-label'},t('secret')),h('input',{className:'sn-input',type:showSecrets?'text':'password',placeholder:k.configured?t('keep'):'',value:k.keyText,disabled:disabled||k.clear||!k.credentialWritable,onChange:e=>p.editKey(k.id,'keyText',e.target.value)}),h('span',{className:'sn-meta'},`${k.ref}${k.source?' · '+t('source')+': '+k.source:''}${k.credentialWritable?' · '+t('writable'):' · '+t('readOnlySecret')}`))),h('div',{className:'sn-actions',style:{marginTop:'8px'}},(k.status==='disabled'||k.status==='cooldown')?h('button',{className:'sn-btn',disabled,onClick:()=>p.resetRuntime(k.id)},t('resetState')):null,k.configured&&k.credentialWritable?h('button',{className:'sn-btn',disabled,onClick:()=>p.toggleKeyClear(k.id)},k.clear?t('undo'):t('clear')):null,h('span',{className:'sn-spacer'}),h('button',{className:'sn-link sn-danger',disabled:disabled||s.keys.length<=1,onClick:()=>p.removeKey(k.id)},t('remove'))))),h('div',{style:{padding:'0 0 12px'}},h('button',{className:'sn-btn',disabled,onClick:p.addKey},t('addKey')))),
      h('div',{className:'sn-card'},h('div',{className:'sn-head'},h('h3',null,t('routing')),h(R,{state:s,f:'modelKeyRules',t,disabled,onReset:()=>p.resetField('modelKeyRules')}),h('button',{className:'sn-link',disabled,onClick:p.addRule},t('addRule'))),h('p',{className:'sn-hint'},t('routingHint')),s.modelKeyRules.length?s.modelKeyRules.map((r,i)=>h('div',{className:'sn-rule',key:i},h('div',{className:'sn-actions'},h('span',{className:'sn-badge'},`#${i+1}`),h('span',{className:'sn-spacer'}),h('button',{className:'sn-link',disabled:disabled||i===0,onClick:()=>p.moveRule(i,-1)},t('up')),h('button',{className:'sn-link',disabled:disabled||i===s.modelKeyRules.length-1,onClick:()=>p.moveRule(i,1)},t('down')),h('button',{className:'sn-link sn-danger',disabled,onClick:()=>p.removeRule(i)},t('remove'))),h('div',{className:'sn-grid'},h('label',{className:'sn-field'},h('span',{className:'sn-label'},t('models')),h('select',{className:'sn-select sn-multi',multiple:true,value:r.models,disabled,onChange:e=>p.editRule(i,'models',Array.from(e.target.selectedOptions).map(o=>o.value))},s.catalog.map(m=>h('option',{key:m.id,value:m.id},m.name||m.id)))),h('label',{className:'sn-field'},h('span',{className:'sn-label'},t('key')),h('select',{className:'sn-select',value:r.keyId,disabled,onChange:e=>p.editRule(i,'keyId',e.target.value)},s.keys.map(k=>h('option',{key:k.id,value:k.id},k.label))))))):h('p',{className:'sn-hint',style:{padding:'8px 0 12px'}},t('noRules'))),
      h('div',{className:'sn-card'},h('div',{className:'sn-head'},h('h3',null,t('allow')),h(R,{state:s,f:'visibleModels',t,disabled,onReset:()=>p.resetField('visibleModels')}),h('button',{className:'sn-link',disabled,onClick:p.showAllModels},t('showAll')),h('button',{className:'sn-link',onClick:p.refreshModels},t('refreshModels'))),h('p',{className:'sn-hint'},t('allowHint')),s.catalogFailed?h('p',{className:'sn-error'},t('catalogFail')):null,h('div',{className:'sn-models'},s.catalog.map(m=>h('label',{className:'sn-check',key:m.id},h('input',{type:'checkbox',checked:chosen.has(m.id),disabled,onChange:e=>p.toggleVisibleModel(m.id,e.target.checked)}),h('span',null,m.name||m.id),m.name&&m.name!==m.id?h('span',{className:'sn-meta'},m.id):null)))),
      h('div',{className:'sn-card'},h('button',{className:'sn-advanced',onClick:()=>setAdv(v=>!v)},`${t('advanced')} ${adv?'▴':'▾'}`),adv?h('div',null,[['apiBase','apiBase'],['cooldown429Ms','cd'],['maxCooldown429Ms','maxCd'],['connectTimeoutMs','connect'],['streamIdleTimeoutMs','idle'],['defaultContextWindow','context']].map(([f,l])=>h(Field,{key:f,state:s,f,label:t(l),t,disabled,edit:p.edit,reset:p.resetField}))):null),
      h('div',{className:'sn-card'},h('div',{className:'sn-head'},h('h3',null,t('quota'))),h('p',{className:'sn-hint',style:{paddingBottom:'12px'}},t('quotaHint'))),h('div',{className:'sn-footer'},s.failed?h('p',{className:'sn-error'},t('saveFail')):(!s.valid&&s.dirty?h('p',{className:'sn-error'},t('invalid')):(s.saved&&!s.dirty?h('p',{className:'sn-ok'},t('saved')):h('span',{className:'sn-spacer'}))),h('button',{className:'sn-btn',disabled:disabled||!s.dirty,onClick:p.discard},t('cancel')),h('button',{className:'sn-btn sn-primary',disabled:disabled||!s.dirty||!s.valid,onClick:p.save},s.saving?t('saving'):t('save'))))}
    const EDITOR_SLOT='settings.models.provider-card',EDITOR_TOKEN=/(?:^|_)(?:editor|addBlock)$/
    function classTokens(el){return el&&typeof el.className==='string'?el.className.split(/\s+/).filter(Boolean):[]}
    function isEditorRoot(el){return classTokens(el).some(t=>EDITOR_TOKEN.test(t))}
    function resolveAnchor(root){if(!root)return null;const sel=`[data-slot="${EDITOR_SLOT}"]`;if(typeof root.closest==='function'){const hit=root.closest(sel);if(hit)return hit}return root.parentElement||null}
    function resolveCardContainer(anchor){let node=anchor?anchor.parentElement:null;while(node){if(node.tagName==='LI')return node;node=node.parentElement}return anchor?anchor.parentElement:null}
    function editor(wrapper){if(!wrapper)return null;for(const x of [wrapper.nextElementSibling,wrapper.previousElementSibling])if(isEditorRoot(x))return x;return null}
    function attachEditorSuppression(root,setOpen){if(!root||typeof MutationObserver==='undefined')return()=>{};const anchor=resolveAnchor(root),row=resolveCardContainer(anchor);if(!anchor||!row)return()=>{};const hidden=new Map();const hide=el=>{if(!el||hidden.has(el)||!el.style)return;hidden.set(el,typeof el.style.display==='string'?el.style.display:'');el.style.display='none'};const restore=()=>{for(const [el,prev] of hidden){try{el.style.display=prev}catch(e){}}hidden.clear()};const sync=()=>{const e=editor(anchor);if(e)hide(e);const next=!!e;setOpen(prev=>prev===next?prev:next)};sync();const o=new MutationObserver(sync);o.observe(row,{childList:true,subtree:true});return()=>{o.disconnect();restore()}}
    function Card(p){const s=p.useSenseNovaSettings(x=>x),ref=React.useRef(null),[open,setOpen]=React.useState(false);React.useEffect(()=>attachEditorSuppression(ref.current,setOpen),[]);return h('div',{ref,className:'sn-modelCard',style:open?undefined:{display:'none'}},open?h('span',{className:'sn-badge'},s.keys.some(k=>k.configured)?p.t('usable'):p.t('missing')):null,open?h('span',{className:'sn-meta'},p.t('intro')):null)}
    const desc=[{id:`${PKG}#sensenova/runtime`,service:'senseNovaRuntime',namespace:'sensenova',method:'runtime',invocation:{kind:'direct'},parameters:[],result:{mode:'src-json'}},{id:`${PKG}#sensenova/reset`,service:'senseNovaRuntime',namespace:'sensenova',method:'reset',invocation:{kind:'direct'},parameters:[{name:'id',wire:'id',source:'json',codec:{mode:'src-json'}}],result:{mode:'src-json'}},{id:`${PKG}#sensenova/models`,service:'senseNovaRuntime',namespace:'sensenova',method:'models',invocation:{kind:'direct'},parameters:[],result:{mode:'src-json'}}]
    function apply(ctx){ctx.effect(()=>ctx.locale.register(LNS,{zh,en}),'sensenova locale');ctx.effect(()=>css(),'sensenova styles');const c=new Controller(ctx.settingsScope.bind({namespace:NS}),ctx.remote.credentials,ctx.remote.llm),st=store(c);ctx.effect(()=>()=>{st.dispose();c.dispose()},'sensenova controller');if(ctx.remote?.$on)ctx.effect(()=>ctx.remote.$on('credentials/reference-updated',()=>c.refreshCreds()),'sensenova creds');if(ctx.remote?.$mount)ctx.effect(()=>{let stop=false,unmount;void ctx.remote.$mount({package:PKG,descriptors:desc}).then(d=>{if(stop){void d();return}unmount=d;ctx.inject(['remote.sensenova'],x=>c.setRuntimeApi(x.remote.sensenova))}).catch(console.error);return()=>{stop=true;if(unmount)void unmount()}},'sensenova remote');const injected=()=>({hooks:{senseNovaSettings:st},edit:(f,v)=>c.edit(f,v),resetField:f=>c.reset(f),editKey:(id,f,v)=>c.editKey(id,f,v),toggleKeyClear:id=>c.toggleClear(id),addKey:()=>c.addKey(),removeKey:id=>c.removeKey(id),refreshRuntime:()=>void c.refreshRuntime(),resetRuntime:id=>void c.resetRuntime(id),addRule:()=>c.addRule(),removeRule:i=>c.removeRule(i),moveRule:(i,d)=>c.moveRule(i,d),editRule:(i,f,v)=>c.editRule(i,f,v),toggleVisibleModel:(id,on)=>c.toggleModel(id,on),showAllModels:()=>c.showAll(),refreshModels:()=>void c.refreshModels(),discard:()=>c.discard(),save:()=>void c.save()});const t=ctx.locale.bind(LNS);ctx.slots.inject('settings.section',()=>ctx.slots.register({name:'settings.section',id:'sensenova',order:13,label:()=>t('nav'),locale:LNS,inject:injected},Page));ctx.slots.inject('settings.models.provider-card',()=>ctx.slots.register({name:'settings.models.provider-card',key:NS,locale:LNS,inject:injected},Card))}
    const inject=['slots','locale','remote','remote.credentials','remote.llm','settingsScope'];exports.apply=apply;exports.inject=inject;exports.__internals={classTokens,isEditorRoot,resolveAnchor,resolveCardContainer,editor,attachEditorSuppression,Controller};return module.exports
  }
})
